# Generated by Django 5.2 on 2025-09-04 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_promocode_order_discount_amount_order_applied_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='percent_off',
            field=models.DecimalField(decimal_places=2, help_text='Enter percent discount as a number, e.g. 10 = 10%.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
