# Generated by Django 5.2 on 2025-05-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('bouquet', 'Bouquet'), ('coffee', 'Coffee'), ('bundle', 'Bundle')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('special_offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
