# Generated by Django 5.2 on 2025-09-01 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'ordering': ['-added_on']},
        ),
    ]
